defmodule OpenchatWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :openchat

  # Sessions are encrypted and signed; only a revocable opaque token is stored.
  @session_options [
    store: :cookie,
    key: "_openchat_key",
    signing_salt: "WRsLrKdC",
    same_site: "Strict",
    encryption_salt: "encrypted-session-v1",
    http_only: true,
    secure: Application.compile_env(:openchat, :secure_cookies, false),
    max_age: 86400
  ]

  socket "/socket", OpenchatWeb.UserSocket, websocket: [max_frame_size: 65_536], longpoll: false

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :openchat,
    gzip: not code_reloading?,
    only: OpenchatWeb.static_paths()

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :openchat
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :json],
    length: 150_000,
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug OpenchatWeb.Router
end
