<script>
  import {untrack} from 'svelte';
  import {api} from './api.js';
  import {Button} from '$lib/components/ui/button';
  import {Input} from '$lib/components/ui/input';
  import {Badge} from '$lib/components/ui/badge';
  import * as Card from '$lib/components/ui/card';
  import * as Tabs from '$lib/components/ui/tabs';
  import Icon from './Icon.svelte';
  let {user,version,onmessage,onprofile=()=>{},oncreate=()=>{},onjoin=()=>{}}=$props();
  let friends=$state([]),target=$state(''),search=$state(''),error=$state(''),notice=$state(''),busy=$state(false),loading=$state(true),filter=$state('accepted'),removing=$state(null);
  const accepted=$derived(friends.filter(f=>f.status==='accepted'));
  const pending=$derived(friends.filter(f=>f.status!=='accepted'));
  const matching=$derived((filter==='accepted'?accepted:pending).filter(f=>(f.peer.name+' '+(f.peer.username||'')).toLowerCase().includes(search.toLowerCase())));
  const initials=(name='')=>name.split(' ').map(s=>s[0]).join('').slice(0,2).toUpperCase();
  $effect(()=>{version;untrack(()=>refresh());});
  async function refresh(){try{friends=(await api('/friends')).friends;}catch(e){error=e.message;}finally{loading=false;}}
  async function action(path,method,body){busy=true;error='';notice='';try{await api(path,method,body);if(method==='POST'){notice='Demande envoyée ! Votre ami peut maintenant l’accepter.';target='';filter='pending';}removing=null;await refresh();}catch(e){error=e.message;}finally{busy=false;}}
</script>
<div class="friends-page-content">
  <div class="friends-welcome"><div><span class="eyebrow">LES BONS MOMENTS COMMENCENT ICI</span><h2>Salut, {user.name}<span class="greeting-spark"><Icon name="spark" size={28}/></span></h2><p>Une petite discussion, un grand projet, ou juste un bonjour.</p></div><Badge variant="secondary"><span class="status-dot"></span>Votre espace, votre rythme</Badge></div>
  <div class="friends-layout"><div class="friends-main">
  <Card.Root class="add-friend-card"><Card.Content><div class="card-title-line"><span class="tile-icon peach"><Icon name="users" size={24}/></span><div><h3>À plusieurs, c’est encore mieux.</h3><p>Ajoutez un ami avec son pseudo et lancez la conversation.</p></div></div><form id="add-friend-form" class="friend-add-form" onsubmit={e=>{e.preventDefault();action('/friends','POST',{username:target.trim()});}}><label class="sr-only" for="friend-id">Pseudo de votre ami</label><Input id="friend-id" bind:value={target} required placeholder="@pseudo_de_votre_ami" autocomplete="off"/><Button type="submit" disabled={busy||!target.trim()}><Icon name="plus" size={17}/>Ajouter un ami</Button></form>{#if user.username}<p class="friend-code">Vos amis vous retrouvent avec <strong>@{user.username}</strong></p>{:else}<button class="text-button friend-code" onclick={onprofile}>Choisir mon pseudo pour être retrouvé <Icon name="arrow" size={14}/></button>{/if}</Card.Content></Card.Root>
  {#if error}<p class="error-box" role="alert">{error}</p>{/if}{#if notice}<p class="notice-box" role="status">{notice}</p>{/if}
  <Tabs.Root bind:value={filter} class="friends-tabs"><div class="friend-list-toolbar"><Tabs.List><Tabs.Trigger value="accepted">Mes amis <span class="count-pill">{accepted.length}</span></Tabs.Trigger><Tabs.Trigger value="pending">Demandes {#if pending.length}<span class="count-pill">{pending.length}</span>{/if}</Tabs.Trigger></Tabs.List><div class="friend-search"><Icon name="search" size={16}/><Input id="friend-search" aria-label="Rechercher parmi mes amis" bind:value={search} placeholder="Rechercher…"/></div></div>
  {#each ['accepted','pending'] as tab}<Tabs.Content value={tab}><div id={tab==='accepted'?'friends-list':'friend-requests'} class="friends-list">{#if loading}<p class="loading-note">On retrouve vos amis…</p>{:else}{#each matching as friend (friend.id)}<article class="friend-row"><div class="avatar">{#if friend.peer.avatar}<img src={friend.peer.avatar} alt=""/>{:else}{initials(friend.peer.name)}{/if}</div><div class="friend-identity"><strong>{friend.peer.name}</strong><small>{friend.status==='accepted'?(friend.peer.status||'@'+(friend.peer.username||'ami')):friend.status==='incoming'?'Vous a envoyé une demande':'En attente de sa réponse'}</small></div><div class="friend-actions">{#if friend.status==='incoming'}<Button disabled={busy} onclick={()=>action(`/friends/${friend.id}`,'PUT')}>Accepter</Button>{/if}{#if friend.status==='accepted'}<Button variant="secondary" onclick={()=>onmessage(friend.peer)}><Icon name="chat" size={17}/>Discuter</Button>{/if}<Button variant="ghost" disabled={busy} aria-label={friend.status==='accepted'?`Retirer ${friend.peer.name} des amis`:friend.status==='incoming'?'Refuser la demande':'Annuler la demande'} onclick={()=>friend.status==='accepted'?removing=friend.id:action(`/friends/${friend.id}`,'DELETE')}><Icon name="close" size={16}/>{friend.status==='accepted'?'':friend.status==='incoming'?'Refuser':'Annuler'}</Button></div>{#if removing===friend.id}<div class="friend-remove-confirm"><span>Retirer {friend.peer.name} de vos amis ?</span><Button variant="destructive" disabled={busy} onclick={()=>action(`/friends/${friend.id}`,'DELETE')}>Retirer</Button><Button variant="ghost" onclick={()=>removing=null}>Garder</Button></div>{/if}</article>{:else}<div class="friends-empty"><span class="empty-icon"><Icon name={filter==='accepted'?'chat':'check'} size={32}/></span><h3>{search?'Personne sous ce nom.':filter==='accepted'?'Votre prochain bonjour est ici.':'Vous êtes à jour !'}</h3><p>{search?'Essayez un autre nom ou pseudo.':filter==='accepted'?'Ajoutez votre premier ami avec le champ ci-dessus.':'Les nouvelles demandes d’amitié apparaîtront ici.'}</p></div>{/each}{/if}</div></Tabs.Content>{/each}</Tabs.Root>
  </div><aside class="friends-discover" aria-label="Découvrir Openchat"><Card.Root class="start-server-card"><Card.Content><span class="tile-icon lilac"><Icon name="spark" size={25}/></span><span class="eyebrow">VOTRE BANDE, VOTRE ESPACE</span><h3>Et si on se retrouvait tous ?</h3><p>Un serveur rassemble vos proches autour de salons pour écrire, parler et partager son écran.</p><Button class="w-full" onclick={oncreate}><Icon name="plus" size={16}/>Créer un serveur</Button><Button variant="ghost" class="w-full" onclick={onjoin}>J’ai une invitation <Icon name="arrow" size={15}/></Button></Card.Content></Card.Root><div class="privacy-card"><span class="tile-icon mint"><Icon name="lock" size={22}/></span><h3>Entre vous, vraiment.</h3><p>Vos messages sont chiffrés. Les conversations restent entre leurs participants.</p></div></aside></div>
</div>
