<script>
  import {onMount} from 'svelte';
  import {Button} from '$lib/components/ui/button';
  import {Switch} from '$lib/components/ui/switch';
  import {Input} from '$lib/components/ui/input';
  import {api} from './api.js';
  import {permissions,defaults} from './permissions.js';
  import Icon from './Icon.svelte';
  let {server,members,onchange}= $props();
  let roles=$state([]),everyone=$state([]),held=$state([]),canManage=$state(false);
  let selected=$state('everyone'),name=$state(''),emoji=$state(''),color=$state('#607d69'),values=$state([]),busy=$state(true),loaded=$state(false),error=$state(''),saved=$state(''),confirmDelete=$state(false);
  const editable=$derived(canManage&&(selected==='everyone'||selected==='new'||roles.find(r=>r.id===selected)?.editable));
  onMount(async()=>{try{await load();choose('everyone');loaded=true;}catch(e){error=e.message;}finally{busy=false;}});
  async function load(){const data=await api(`/servers/${server.id}/roles`);roles=data.roles;everyone=data.everyone;held=data.permissions;canManage=data.can_manage_roles;}
  function choose(id){selected=id;saved='';error='';confirmDelete=false;const role=roles.find(r=>r.id===id);name=role?.name||'';emoji=role?.emoji||'';color=role?.color||'#607d69';values=[...(id==='everyone'?everyone:role?.permissions||[])];}
  function toggle(id){values=values.includes(id)?values.filter(v=>v!==id):[...values,id];saved='';}
  async function run(fn,message){if(!loaded||busy)return;busy=true;error='';saved='';try{await fn();await load();await onchange();saved=message;}catch(e){error=e.message;}finally{busy=false;}}
  async function save(e){e.preventDefault();await run(async()=>{if(selected==='everyone')await api(`/servers/${server.id}/everyone`,'PUT',{permissions:values});else{const result=await api(`/servers/${server.id}/roles${selected==='new'?'':'/'+selected}`,selected==='new'?'POST':'PUT',{name,color,emoji,permissions:values});selected=result.id;}},'Le rôle et ses droits ont été enregistrés.');}
  function preset(kind){name=kind==='admin'?'Administrateur':kind==='moderator'?'Modérateur':'Membre';values=(kind==='admin'?['administrator']:kind==='moderator'?[...defaults,'manage_threads','manage_channels','invite']:defaults).filter(p=>held.includes(p));}
  async function move(index,offset){const ids=roles.map(r=>r.id);[ids[index],ids[index+offset]]=[ids[index+offset],ids[index]];await run(()=>api(`/servers/${server.id}/role-order`,'PUT',{role_ids:ids}),'La hiérarchie a été enregistrée.');}
  async function remove(){await run(async()=>{await api(`/servers/${server.id}/roles/${selected}`,'DELETE');choose('everyone');},'Le rôle a été supprimé des membres et des salons.');}
</script>
<div class="role-owner-note"><Icon name="shield" size={21}/><div><strong>Propriétaire · {members.find(m=>m.id===server.owner_id)?.name||'Créateur du serveur'}</strong><p>Au-dessus de tous les rôles, avec tous les droits. Ce statut ne peut pas être attribué par un rôle.</p></div></div>
{#if error}<p class="error-box" role="alert">{error}</p>{/if}

<div class="role-hierarchy" id="role-hierarchy"><p class="settings-explanation">Du plus élevé au plus bas. Vous pouvez gérer uniquement les rôles inférieurs au vôtre.</p>{#each roles as role,index (role.id)}<div class="hierarchy-row" class:active={selected===role.id}><button type="button" class="hierarchy-name" onclick={()=>choose(role.id)}><span class="role-dot" style:background={role.color}></span><strong>{role.emoji ? role.emoji+' ' : ''}{role.name}</strong><small>{role.permissions.includes('administrator')?'Administrateur':`${members.filter(m=>m.role_ids?.includes(role.id)).length} membre(s)`}{role.editable?'':' · protégé'}</small></button><button id={`role-up-${role.id}`} type="button" class="icon-button" aria-label={`Monter ${role.name}`} disabled={busy||!role.editable||!roles[index-1]?.editable} onclick={()=>move(index,-1)}>↑</button><button id={`role-down-${role.id}`} type="button" class="icon-button" aria-label={`Descendre ${role.name}`} disabled={busy||!role.editable||!roles[index+1]?.editable} onclick={()=>move(index,1)}>↓</button></div>{/each}</div>
<form onsubmit={save} id="role-form"><div class="role-editor-navigation"><Button type="button" variant={selected==='everyone'?'secondary':'outline'} onclick={()=>choose('everyone')} disabled={busy}>@everyone</Button>{#if canManage}<Button id="create-role" type="button" variant="outline" onclick={()=>choose('new')} disabled={busy}><Icon name="plus" size={16}/>Créer un rôle</Button>{/if}</div><h3 class="role-editor-heading">{selected==='everyone'?'Droits de tous les membres':selected==='new'?'Nouveau rôle':`${emoji} ${name}`}</h3>
{#if !editable&&loaded}<p class="settings-explanation">Ce rôle est protégé par la hiérarchie. Vous pouvez consulter ses permissions.</p>{/if}
<fieldset disabled={busy||!editable}>
{#if selected!=='everyone'}<div class="field-row"><div><label for="role-name">Nom du rôle · propre à ce serveur</label><Input id="role-name" bind:value={name} required minlength={2} maxlength={40} placeholder="Ex. Équipe, Amis, Modérateurs"/></div><div><label for="role-color">Couleur</label><input id="role-color" type="color" bind:value={color}/></div></div><div class="role-emoji-editor"><label for="role-emoji">Emoji du rôle <span class="muted">· facultatif</span></label><Input id="role-emoji" bind:value={emoji} maxlength={32} placeholder="Ex. 🌿" aria-describedby="role-emoji-help"/><p id="role-emoji-help" class="settings-explanation">Choisissez un emoji ou collez le vôtre. Il apparaîtra à côté du nom du rôle.</p><div class="role-emoji-choices">{#each ['🌿','⭐','🛡️','🎮','🎨','💬','🔥','👑','🚀','🤝'] as choice}<button type="button" aria-label={`Choisir ${choice}`} aria-pressed={emoji===choice} onclick={()=>{emoji=choice;saved='';}}>{choice}</button>{/each}<button type="button" class="text-button" onclick={()=>{emoji='';saved='';}}>Sans emoji</button></div></div><div class="preset-row"><span>Modèles :</span><button type="button" onclick={()=>preset('member')}>Membre</button><button type="button" onclick={()=>preset('moderator')}>Modérateur</button>{#if held.includes('administrator')}<button id="administrator-preset" type="button" onclick={()=>preset('admin')}>Administrateur</button>{/if}</div>{:else}<p class="settings-explanation">Ces droits s’appliquent à tous les membres. Les rôles ajoutent des droits, puis les exceptions des salons s’appliquent.</p>{/if}
{#if values.includes('administrator')}<p class="admin-role-note"><Icon name="shield" size={18}/>Administrateur donne tous les droits et l’accès aux salons privés. La hiérarchie des rôles reste applicable.</p>{/if}
<div class="permission-list">{#each permissions.filter(p=>p.id!=='manage_roles'&&(selected!=='everyone'||p.id!=='administrator')) as permission}<label class="permission-row" for={`role-permission-${permission.id}`}><span><strong>{permission.label}</strong><small>{permission.description}</small></span><Switch id={`role-permission-${permission.id}`} checked={values.includes(permission.id)} disabled={busy||!editable||!held.includes(permission.id)} onCheckedChange={()=>toggle(permission.id)}/></label>{/each}</div>
</fieldset>
<div class="settings-save"><span role="status">{saved}</span><Button id="save-role" type="submit" disabled={busy||!loaded||!editable}><Icon name="check" size={16}/>{busy?'Enregistrement…':'Enregistrer les droits'}</Button></div></form>
{#if editable&&!['new','everyone'].includes(selected)}<div class="role-delete">{#if confirmDelete}<p>Supprimer « {name} » ? Ce rôle sera retiré de tous les membres et des exceptions des salons.</p><Button id="confirm-delete-role" variant="destructive" disabled={busy} onclick={remove}>Confirmer la suppression</Button><Button variant="ghost" disabled={busy} onclick={()=>confirmDelete=false}>Annuler</Button>{:else}<button id="delete-role" class="text-button" disabled={busy} onclick={()=>confirmDelete=true}>Supprimer ce rôle</button>{/if}</div>{/if}
